"use client";

import { useRef, useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useResults } from "./ResultsContext";
import { useCustomization } from "./CustomizationContext";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import type { TopTraitsReportResult } from "@/lib/top-traits-report-service";
import { trackTopTraitsReportGenerated, trackReportOpenedInChat } from "@/lib/analytics";

type Phase = 'idle' | 'generating' | 'complete' | 'error';

interface TopTraitsReportModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TopTraitsReportModal({ isOpen, onClose }: TopTraitsReportModalProps) {
  const router = useRouter();
  const { savedResults } = useResults();
  const { customization } = useCustomization();

  const [phase, setPhase] = useState<Phase>('idle');
  const [message, setMessage] = useState('');
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<TopTraitsReportResult | null>(null);
  const [questions, setQuestions] = useState<string[]>([]);
  const [traitsExpanded, setTraitsExpanded] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inFlightRef = useRef(false);
  const progressTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (phase === 'generating') {
      progressTimerRef.current = setInterval(() => {
        setProgress(p => p < 88 ? p + 1 : p);
      }, 450);
    } else {
      if (progressTimerRef.current) clearInterval(progressTimerRef.current);
    }
    return () => { if (progressTimerRef.current) clearInterval(progressTimerRef.current); };
  }, [phase]);

  const handleGenerate = async () => {
    if (inFlightRef.current) return;
    inFlightRef.current = true;
    setPhase('generating');
    setMessage('Selecting top 50 signals by effect size…');
    setProgress(10);
    setError(null);
    setResult(null);

    try {
      const { generateTopTraitsReport } = await import('@/lib/top-traits-report-service');
      const res = await generateTopTraitsReport(savedResults, customization, (update) => {
        setMessage(update.message);
        setProgress(update.progress);
      });
      setResult(res);
      setQuestions(res.questions ?? []);
      setProgress(100);
      setPhase('complete');
      trackTopTraitsReportGenerated(res.selected.length);
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Generation failed.';
      setError(msg.includes('429') ? 'nilAI is rate-limited. The service retried automatically but is still overloaded. Wait 30-60 seconds and try again.' : msg);
      setPhase('error');
    } finally {
      inFlightRef.current = false;
    }
  };

  const handleCopy = async () => {
    if (!result?.report) return;
    try {
      await navigator.clipboard.writeText(result.report);
      alert('Report copied to clipboard!');
    } catch {
      alert('Failed to copy report to clipboard');
    }
  };

  const handlePrint = () => {
    if (!result?.report) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>Top Traits Report</title><style>
      body { font-family: Georgia, serif; max-width: 800px; margin: 2rem auto; line-height: 1.7; color: #1a1a1a; }
      h1 { font-size: 1.8rem; border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
      h2 { font-size: 1.3rem; margin-top: 2rem; color: #2a2a2a; }
      h3 { font-size: 1.1rem; color: #333; }
      li { margin-bottom: 0.4rem; }
      footer { margin-top: 3rem; border-top: 1px solid #ccc; padding-top: 1rem; font-size: 0.8rem; color: #888; }
    </style></head><body>
    <h1>Top Traits Report</h1>
    <p style="color:#666;font-size:0.9rem">Generated ${new Date().toLocaleString()}</p>
    <div>${result.report.replace(/\n/g, '<br>')}</div>
    <footer>Generated by Monadic DNA Explorer • For educational purposes only</footer>
    </body></html>`);
    win.document.close();
    win.print();
  };

  const handleOpenInChat = (question?: string) => {
    if (!result?.report) return;
    trackReportOpenedInChat('top_traits', !!question);
    localStorage.setItem('health_report_context', result.report);
    router.push(question ? `/dna-chat?q=${encodeURIComponent(question)}` : '/dna-chat');
  };

  const handleClose = () => {
    if (phase === 'generating') return;
    setPhase('idle');
    setResult(null);
    setQuestions([]);
    setTraitsExpanded(false);
    setError(null);
    setProgress(0);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="modal-overlay" onClick={handleClose}>
      <div className="modal-content large-modal" onClick={e => e.stopPropagation()}>
        <button
          className="close-button"
          onClick={handleClose}
          disabled={phase === 'generating'}
          style={{
            position: 'absolute', top: '1rem', right: '1rem', zIndex: 10,
            background: 'var(--surface-bg)', border: '1px solid var(--border-color)',
            borderRadius: '6px', width: '32px', height: '32px',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: '1.5rem', cursor: phase === 'generating' ? 'default' : 'pointer',
            color: 'var(--text-primary)', opacity: phase === 'generating' ? 0.4 : 1,
          }}
        >×</button>

        <div className="modal-body">

          {/* Idle */}
          {phase === 'idle' && (
            <div style={{ background: 'var(--modal-bg)', borderRadius: '8px', padding: '1.5rem' }}>
              <h2 style={{ color: 'var(--text-primary)', marginTop: 0 }}>Top Traits Report</h2>
              <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6 }}>
                Takes the 100 strongest genetic associations by effect size from your results and synthesizes what they reveal about your biology. No domain filtering or health history anchoring; just your highest-signal variants.
              </p>
              <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem' }}>
                <button
                  className="primary-button"
                  onClick={handleGenerate}
                  disabled={savedResults.length === 0}
                >
                  {savedResults.length === 0 ? 'Load results first' : 'Generate Top Traits Report'}
                </button>
              </div>
              <p style={{ marginTop: '1rem', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                {savedResults.length.toLocaleString()} saved results available · Top 100 by effect size · ~30 seconds
              </p>
            </div>
          )}

          {/* Generating */}
          {phase === 'generating' && (
            <div style={{ background: 'var(--modal-bg)', borderRadius: '8px', padding: '2rem', textAlign: 'center' }}>
              <div style={{ marginBottom: '1.5rem' }}>
                <div className="loading-spinner" style={{ margin: '0 auto 1rem' }} />
                <p style={{ color: 'var(--text-primary)', fontWeight: 600, fontSize: '1rem', marginBottom: '0.25rem' }}>
                  Generating Top Traits Report
                </p>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem' }}>{message}</p>
              </div>
              <div style={{ background: 'var(--surface-bg)', borderRadius: '8px', height: '8px', overflow: 'hidden' }}>
                <div style={{
                  height: '100%', borderRadius: '8px',
                  background: 'linear-gradient(90deg, #f59e0b, #d97706)',
                  width: `${progress}%`,
                  transition: 'width 0.45s ease',
                }} />
              </div>
              <p style={{ marginTop: '0.5rem', fontSize: '0.78rem', color: 'var(--text-secondary)' }}>
                This may take 20–40 seconds depending on the provider.
              </p>
            </div>
          )}

          {/* Error */}
          {phase === 'error' && (
            <div style={{ background: 'var(--modal-bg)', borderRadius: '8px', padding: '2rem', textAlign: 'center' }}>
              <p style={{ color: '#dc2626', marginBottom: '1rem' }}>Generation failed: {error}</p>
              <button className="secondary-button" onClick={() => setPhase('idle')}>Try Again</button>
            </div>
          )}

          {/* Complete */}
          {phase === 'complete' && result && (
            <div style={{ background: 'var(--modal-bg)', borderRadius: '8px', padding: '1.5rem' }}>
              <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
                <button className="secondary-button" onClick={handleOpenInChat}>💬 Discuss in DNA Chat</button>
                <button className="secondary-button" onClick={handleCopy}>📋 Copy</button>
                <button className="secondary-button" onClick={handlePrint}>🖨️ Print</button>
                <button className="secondary-button" onClick={() => setPhase('idle')}>↺ Regenerate</button>
              </div>

              <div style={{
                background: 'var(--surface-bg)', border: '1px solid var(--border-color)',
                borderRadius: '6px', padding: '0.75rem 1rem', marginBottom: '1.25rem',
                fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.6,
              }}>
                <strong style={{ color: 'var(--text-primary)' }}>Generated:</strong> {new Date().toLocaleString()}<br />
                <strong style={{ color: 'var(--text-primary)' }}>Based on:</strong> top {result.selected.length} associations by effect size from {savedResults.length.toLocaleString()} saved results
              </div>

              <div style={{
                background: 'rgba(234,179,8,0.08)', border: '1px solid rgba(234,179,8,0.25)',
                borderRadius: '6px', padding: '0.6rem 0.9rem', marginBottom: '1.25rem',
                fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.5,
              }}>
                These are population-level associations from GWAS studies, not individual predictions. Effect sizes reflect averages across large cohorts. Do not use this report for medical decisions.
              </div>

              <div className="markdown-content" style={{ color: 'var(--text-primary)', lineHeight: '1.7' }}>
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{result.report}</ReactMarkdown>
              </div>

              {questions.length > 0 && (
                <div style={{ marginTop: '2rem', borderTop: '1px solid var(--border-color)', paddingTop: '1rem' }}>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.6rem', marginTop: 0 }}>
                    Ask in DNA Chat:
                  </p>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                    {questions.map((q, i) => (
                      <button
                        key={i}
                        onClick={() => handleOpenInChat(q)}
                        style={{
                          background: 'var(--surface-bg)', border: '1px solid var(--border-color)',
                          borderRadius: '6px', padding: '0.5rem 0.75rem',
                          fontSize: '0.83rem', color: 'var(--text-primary)',
                          cursor: 'pointer', textAlign: 'left', lineHeight: 1.4,
                        }}
                        onMouseEnter={e => (e.currentTarget.style.borderColor = 'var(--accent-color)')}
                        onMouseLeave={e => (e.currentTarget.style.borderColor = 'var(--border-color)')}
                      >
                        💬 {q}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <div style={{ marginTop: '2rem', borderTop: '1px solid var(--border-color)', paddingTop: '1rem' }}>
                <button
                  onClick={() => setTraitsExpanded(e => !e)}
                  style={{
                    background: 'none', border: 'none', cursor: 'pointer',
                    color: 'var(--text-secondary)', fontSize: '0.85rem', padding: 0,
                    display: 'flex', alignItems: 'center', gap: '0.4rem'
                  }}
                >
                  <span>{traitsExpanded ? '▾' : '▸'}</span>
                  <span>{result.selected.length} associations used in this report</span>
                </button>
                {traitsExpanded && (
                  <div style={{ marginTop: '0.75rem', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                    {result.selected.map((r, i) => {
                      const dir = r.riskLevel === 'increased' ? '↑' : r.riskLevel === 'decreased' ? '↓' : '→';
                      const effect = r.effectType === 'OR'
                        ? `OR ${r.riskScore.toFixed(2)}x`
                        : `β=${r.riskScore >= 0 ? '+' : ''}${r.riskScore.toFixed(3)}`;
                      return (
                        <div key={`${r.studyId}-${i}`} style={{
                          display: 'flex', gap: '0.5rem', padding: '0.25rem 0',
                          borderBottom: '1px solid var(--border-color)', alignItems: 'baseline'
                        }}>
                          <span style={{
                            color: r.riskLevel === 'increased' ? '#ef4444' : r.riskLevel === 'decreased' ? '#22c55e' : 'var(--text-secondary)',
                            fontWeight: 600, minWidth: '1rem'
                          }}>{dir}</span>
                          <span style={{ flex: 1, color: 'var(--text-primary)' }}>{r.traitName}</span>
                          <span style={{ whiteSpace: 'nowrap' }}>{effect}</span>
                          {r.mappedGene && <span style={{ whiteSpace: 'nowrap', color: 'var(--accent-color)' }}>{r.mappedGene}</span>}
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>

              <div style={{
                marginTop: '1.5rem', paddingTop: '1rem',
                borderTop: '1px solid var(--border-color)',
                color: 'var(--text-secondary)', fontSize: '0.85rem', textAlign: 'center'
              }}>
                Generated by Monadic DNA Explorer · For educational purposes only
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
